### ISSUE TITLE
Good news!

### ISSUE THREAD

**Issue by Techn1x** [theburningmonk/better-dynamodb-scaling#2]
It looks like AWS have released an "on-demand" mode which provides instant autoscaling (rather than the the slow autoscaler used with provisioned mode).

https://aws.amazon.com/blogs/aws/amazon-dynamodb-on-demand-no-capacity-planning-and-pay-per-request-pricing/

Depending on your requirements, on-demand may be more expensive and you may still want to use provisioned through-put but with a faster autoscaler, so there might still be a use for this codebase - but I imagine most users with a need for quick autoscaling for large spikes will go for on-demand.

**Comment by theburningmonk** [comment]
I'm gonna rerun the tests against an on-demand table and see how well it handles the traffic patterns I used in the original test. And then publish the result soon.

**Comment by Techn1x** [comment]
Can't wait to read it!
